[project]
name = "opcua-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncua>=1.1.8",
    "fastmcp>=2.14.1",
]
